### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Andromelus** [AntShares/leveldb#1]
According to [this page](http://docs.neo.org/en-us/node/setup.html), I need this repo to setup a windows node.

Ok, I got the repo, but then what? The files do not exist in the repo, what do I have to do?

Solution: Build it with visual studio. However, just a little line saying that in the doc wouldn't hurt anyone...

**Comment by Andromelus** [comment]
Building the project only gives a .lib file.

**Comment by erikzhang** [comment]
![default](https://user-images.githubusercontent.com/10204923/33309569-76e82b90-d459-11e7-8632-656ef20fe6b3.jpg)
You can change the configuration to build it for .dll

**Comment by Andromelus** [comment]
Thank you for the answer. However, when running `dotnet neo-cli.dll` I still have the error that it cannot find the dll even if it is in the folder

http://prntscr.com/hg9d1t

**Comment by erikzhang** [comment]
Try to build a x64 version of leveldb.

**Comment by Andromelus** [comment]
It is already an x64 version.

> 1>leveldb.vcxproj -> C:\Users\Florian Castelain\Desktop\leveldb-master\bin\x64\Debug\libleveldb.dll

**Comment by erikzhang** [comment]
If you are running neo-cli on a different PC (other than the development one), you need to install Microsoft Visual C++ Redistributable

**Comment by Andromelus** [comment]
Thank you! That was it.
